### ISSUE TITLE
Cannot build in 3.17+ kernels

### ISSUE THREAD

**Issue by ogarcia** [CMoH/lg4l#3]
At build time I give this error:

```
make -C /lib/modules/3.18.1-1-ARCH/build M=/home/ogarcia/Documentos/lg4l modules
make[1]: Entering directory '/usr/lib/modules/3.18.1-1-ARCH/build'
  CC [M]  /home/ogarcia/Documentos/lg4l/hid-g19.o
In file included from include/linux/cpumask.h:12:0,
                 from ./arch/x86/include/asm/cpumask.h:4,
                 from ./arch/x86/include/asm/msr.h:10,
                 from ./arch/x86/include/asm/processor.h:20,
                 from ./arch/x86/include/asm/atomic.h:6,
                 from include/linux/atomic.h:4,
                 from include/linux/kgdb.h:18,
                 from include/linux/fb.h:4,
                 from /home/ogarcia/Documentos/lg4l/hid-g19.c:19:
include/linux/bug.h:33:45: error: negative width in bit-field '<anonymous>'
 #define BUILD_BUG_ON_ZERO(e) (sizeof(struct { int:-!!(e); }))
                                             ^
include/linux/kernel.h:815:3: note: in expansion of macro 'BUILD_BUG_ON_ZERO'
   BUILD_BUG_ON_ZERO((perms) & 2) +    \
   ^
include/linux/sysfs.h:75:12: note: in expansion of macro 'VERIFY_OCTAL_PERMISSIONS'
    .mode = VERIFY_OCTAL_PERMISSIONS(_mode) },  \
            ^
include/linux/device.h:540:45: note: in expansion of macro '__ATTR'
  struct device_attribute dev_attr_##_name = __ATTR(_name, _mode, _show, _store)
                                             ^
/home/ogarcia/Documentos/lg4l/hid-g19.c:163:8: note: in expansion of macro 'DEVICE_ATTR'
 static DEVICE_ATTR(fb_update_rate, 0666,
        ^
include/linux/bug.h:33:45: error: negative width in bit-field '<anonymous>'
 #define BUILD_BUG_ON_ZERO(e) (sizeof(struct { int:-!!(e); }))
                                             ^
include/linux/kernel.h:815:3: note: in expansion of macro 'BUILD_BUG_ON_ZERO'
   BUILD_BUG_ON_ZERO((perms) & 2) +    \
   ^
include/linux/sysfs.h:75:12: note: in expansion of macro 'VERIFY_OCTAL_PERMISSIONS'
    .mode = VERIFY_OCTAL_PERMISSIONS(_mode) },  \
            ^
include/linux/device.h:540:45: note: in expansion of macro '__ATTR'
  struct device_attribute dev_attr_##_name = __ATTR(_name, _mode, _show, _store)
                                             ^
/home/ogarcia/Documentos/lg4l/hid-g19.c:449:8: note: in expansion of macro 'DEVICE_ATTR'
 static DEVICE_ATTR(keymap_index, 0666,
        ^
include/linux/bug.h:33:45: error: negative width in bit-field '<anonymous>'
 #define BUILD_BUG_ON_ZERO(e) (sizeof(struct { int:-!!(e); }))
                                             ^
include/linux/kernel.h:815:3: note: in expansion of macro 'BUILD_BUG_ON_ZERO'
   BUILD_BUG_ON_ZERO((perms) & 2) +    \
   ^
include/linux/sysfs.h:75:12: note: in expansion of macro 'VERIFY_OCTAL_PERMISSIONS'
    .mode = VERIFY_OCTAL_PERMISSIONS(_mode) },  \
            ^
include/linux/device.h:540:45: note: in expansion of macro '__ATTR'
  struct device_attribute dev_attr_##_name = __ATTR(_name, _mode, _show, _store)
                                             ^
/home/ogarcia/Documentos/lg4l/hid-g19.c:453:8: note: in expansion of macro 'DEVICE_ATTR'
 static DEVICE_ATTR(keymap, 0666,
        ^
include/linux/bug.h:33:45: error: negative width in bit-field '<anonymous>'
 #define BUILD_BUG_ON_ZERO(e) (sizeof(struct { int:-!!(e); }))
                                             ^
include/linux/kernel.h:815:3: note: in expansion of macro 'BUILD_BUG_ON_ZERO'
   BUILD_BUG_ON_ZERO((perms) & 2) +    \
   ^
include/linux/sysfs.h:75:12: note: in expansion of macro 'VERIFY_OCTAL_PERMISSIONS'
    .mode = VERIFY_OCTAL_PERMISSIONS(_mode) },  \
            ^
include/linux/device.h:540:45: note: in expansion of macro '__ATTR'
  struct device_attribute dev_attr_##_name = __ATTR(_name, _mode, _show, _store)
                                             ^
/home/ogarcia/Documentos/lg4l/hid-g19.c:526:8: note: in expansion of macro 'DEVICE_ATTR'
 static DEVICE_ATTR(name, 0666, g19_name_show, g19_name_store);
        ^
scripts/Makefile.build:263: recipe for target '/home/ogarcia/Documentos/lg4l/hid-g19.o' failed
make[2]: *** [/home/ogarcia/Documentos/lg4l/hid-g19.o] Error 1
Makefile:1381: recipe for target '_module_/home/ogarcia/Documentos/lg4l' failed
make[1]: *** [_module_/home/ogarcia/Documentos/lg4l] Error 2
make[1]: Leaving directory '/usr/lib/modules/3.18.1-1-ARCH/build'
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ogarcia** [comment]
Not bad idea, some device drivers (as nvidia nouveau) use `video` group.

**Comment by CMoH** [comment]
The gnome15 project sets up appropriate permissions for devices using udev rules. I will look for other examples in the kernel code on how to set the defaults. If any of you has a patch ready, please attach it.

**Comment by CMoH** [comment]
Should be solvet by commit 91b0a91
